apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Values.configmap.data.DB_HOST }}"
  DB_PORT: "{{ .Values.configmap.data.DB_PORT }}"
  DB_USER: "{{ .Values.configmap.data.DB_USER }}"
  DB_NAME: "{{ .Values.configmap.data.DB_NAME }}"
  BROKER_HOSTNAME: "{{ .Values.rabbitmq.hostname }}"
  BROKER_PORT: "{{ .Values.rabbitmq.port }}"
  BROKER_USERNAME: "{{ .Values.rabbitmq.username }}"
  BROKER_PASSWORD: "{{ .Values.rabbitmq.password }}"
  BROKER_VIRTUALHOST: "{{ .Values.rabbitmq.virtualhost }}"
  USERID: "{{ .Values.mpConfigMap.data.USERID }}"
  ACCESS_KEY: "{{ .Values.mpConfigMap.data.ACCESS_KEY }}"
  NOTIFICATION_URL: "{{ .Values.mpConfigMap.data.NOTIFICATION_URL }}"
  POS_ID: "{{ .Values.mpConfigMap.data.POS_ID }}"