apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  type: Opaque
data:
  DB_PASSWORD: {{ .Values.configmap.data.DB_PASSWORD| b64enc }}
  BROKER_PASSWORD: {{ .Values.rabbitmq.password| b64enc }}